In [90]:
import pandas as pd

In [91]:
library = pd.read_excel("./library/english_library.xlsx")

In [92]:
result = pd.read_excel("../performance/api/aurora-sdg-multi.xlsx")

In [93]:
result

,Unnamed: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,sum
0,0,0.034044,0.017897,0.021068,0.009639,0.018582,0.007033,0.005853,0.084247,0.042790,0.102992,0.042319,0.014096,0.087421,0.008504,0.013600,0.101853,0.272762,0.884701
1,1,0.050384,0.010348,0.023772,0.016523,0.023367,0.006073,0.008113,0.356905,0.071389,0.086713,0.022753,0.016051,0.042143,0.007357,0.007623,0.135511,0.296534,1.181559
2,2,0.052272,0.009389,0.015048,0.017838,0.015648,0.005253,0.008858,0.443444,0.155738,0.068378,0.026463,0.026227,0.023618,0.006311,0.011389,0.042362,0.320556,1.248793
3,3,0.005450,0.009921,0.004868,0.005811,0.005437,0.016215,0.643865,0.026013,0.085030,0.010522,0.023103,0.147341,0.032688,0.019169,0.051707,0.009069,0.024706,1.120915
4,4,0.073913,0.107120,0.009465,0.018457,0.015185,0.015903,0.029627,0.405517,0.204619,0.033306,0.029814,0.386703,0.015885,0.014109,0.106093,0.021345,0.079793,1.566855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,895,0.021497,0.022889,0.042076,0.021588,0.016054,0.261755,0.014538,0.076736,0.084067,0.033391,0.029826,0.059235,0.046146,0.012518,0.024285,0.023705,0.287584,1.077888
896,896,0.191408,0.012282,0.010240,0.015425,0.025175,0.006436,0.011020,0.472848,0.077163,0.127384,0.029176,0.023347,0.015711,0.005665,0.009276,0.024322,0.099324,1.156201
897,897,0.085181,0.013419,0.011911,0.052014,0.053057,0.006492,0.029164,0.654819,0.174280,0.111903,0.026383,0.058064,0.019180,0.009139,0.018697,0.033676,0.098548,1.455928
898,898,0.022760,0.389083,0.009197,0.012803,0.011995,0.018443,0.033081,0.070935,0.119892,0.013532,0.014156,0.419736,0.015861,0.014444,0.132509,0.014832,0.050447,1.363705
899,899,0.750990,0.047240,0.014868,0.029315,0.023611,0.017630,0.007505,0.057922,0.020766,0.057084,0.030707,0.019527,0.014174,0.009748,0.022926,0.019041,0.023748,1.166802

In [94]:
def detect(n):
    if n >= 0.5:
        return 1
    else:
        return 0

In [95]:
for i in range(1, 18):
    library[i] = library[i].apply(lambda x: detect(x))

In [96]:
for i in range(1, 17):
    result[i] = result[i].apply(lambda x: detect(x))

In [97]:
result

,Unnamed: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,sum
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.272762,0.884701
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.296534,1.181559
2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.320556,1.248793
3,3,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.024706,1.120915
4,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.079793,1.566855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,895,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.287584,1.077888
896,896,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.099324,1.156201
897,897,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0.098548,1.455928
898,898,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.050447,1.363705
899,899,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.023748,1.166802

* Accuracy

In [98]:
def acc(n):
    freq = 0
    summary = len(result)
    for j in range(len(result)):
        if result[n][j] == library[n][j]:
            freq += 1
    return freq/summary

* True Positive

In [99]:
def tp(n):
    freq = 0
    for j in range(len(result)):
        if result[n][j] == 1 and library[n][j] == 1:
            freq += 1 
    return freq

* False Negative

In [100]:
def fn(n):
    freq = 0
    for j in range(len(result)):
        if result[n][j] == 0 and library[n][j] == 1:
            freq += 1 
    return freq

* False Positive

In [101]:
def fp(n):
    freq = 0
    for j in range(len(result)):
        if result[n][j] == 1 and library[n][j] == 0:
            freq += 1 
    return freq

* True Negative

In [102]:
def tn(n):
    freq = 0
    for j in range(len(result)):
        if result[n][j] == 0 and library[n][j] == 0:
            freq += 1 
    return freq

In [103]:
def precision(tp, fp):
    return tp/(tp+fp)

In [104]:
def recall(tp, fn):
    return tp/(tp+fn)

In [105]:
def f1(tp, fn, fp):
    return 2*tp/(2*tp+fn+fp)

In [106]:
performance = pd.read_excel('./result/performance-table.xlsx')

In [107]:
performance

,sdg,True Positive,False Negative,False Positive,True Negative,precision,recall,F1,Acc
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [110]:
for i in range(0, 16):
    performance["True Positive"][i] = tp(i+1)
    performance["False Negative"][i] = fn(i+1)
    performance["False Positive"][i] = fp(i+1)
    performance["True Negative"][i] = tn(i+1)
    performance["precision"][i] = precision(tp=tp(i+1), fp=fp(i+1))
    performance["recall"][i] = recall(tp=tp(i+1), fn=fn(i+1))
    performance["F1"][i] = f1(tp=tp(i+1),fn=fn(i+1),fp=fp(i+1))
    performance["Acc"][i] = acc(i+1)

<ipython-input-110-5b39a003cde3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  performance["True Positive"][i] = tp(i+1)
<ipython-input-110-5b39a003cde3>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  performance["False Negative"][i] = fn(i+1)
<ipython-input-110-5b39a003cde3>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  performance["False Positive"][i] = fp(i+1)
<ipython-input-110-5b39a003cde3>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  performance["True Negative"][i] = tn(i+1)
<ipython-input-110-5b39a003cde3>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  performance["precision"][i] = precision(tp=tp(i+1), fp=fp(i+1))
<ipython-input-110-5b39a003cde3>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  performance["recall"][i] = recall(tp=tp(i+1), fn=fn(i+1))
<ipython-input-110-5b39a003cde3>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  performance["F1"][i] = f1(tp=tp(i+1),fn=fn(i+1),fp=fp(i+1))
<ipython-input-110-5b39a003cde3>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  performance["Acc"][i] = acc(i+1)

In [111]:
performance

,sdg,True Positive,False Negative,False Positive,True Negative,precision,recall,F1,Acc
0,1,31.0,19.0,35.0,815.0,0.469697,0.620000,0.534483,0.940000
1,2,27.0,52.0,13.0,808.0,0.675000,0.341772,0.453782,0.927778
2,3,6.0,56.0,2.0,836.0,0.750000,0.096774,0.171429,0.935556
3,4,3.0,30.0,12.0,855.0,0.200000,0.090909,0.125000,0.953333
4,5,17.0,45.0,9.0,829.0,0.653846,0.274194,0.386364,0.940000
5,6,9.0,26.0,2.0,863.0,0.818182,0.257143,0.391304,0.968889
6,7,9.0,26.0,5.0,860.0,0.642857,0.257143,0.367347,0.965556
7,8,24.0,104.0,3.0,769.0,0.888889,0.187500,0.309677,0.881111
8,9,3.0,97.0,1.0,799.0,0.750000,0.030000,0.057692,0.891111
9,10,12.0,89.0,8.0,791.0,0.600000,0.118812,0.198347,0.892222
10,11,24.0,26.0,8.0,842.0,0.750000,0.480000,0.585366,0.962222
11,12,0.0,11.0,2.0,887.0,0.000000,0.000000,0.000000,0.985556
12,13,55.0,89.0,24.0,732.0,0.696203,0.381944,0.493274,0.874444
13,14,45.0,50.0,2.0,803.0,0.957447,0.473684,0.633803,0.942222
14,15,18.0,105.0,5.0,772.0,0.782609,0.146341,0.246575,0.877778
15,16,22.0,107.0,16.0,755.0,0.578947,0.170543,0.263473,0.863333
16,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [112]:
performance.to_excel('../performance/api/aurora-sdg-multi-performance-2.xlsx')